### ISSUE TITLE
superclass mismatch error

### ISSUE THREAD

**Issue by tielur** [objects-on-rails/display-case#50]
This is very similar to #13. I have several exhibits, and one exhibit I am actually inheriting from another exhibit which causes a `TypeError: superclass mismatch for class Blah2Exhibit`.

I've updated the display_case test app @codeodor originally tested in #13 to reflect what I have and to show the error I'm getting, that can be found here: [tielur/display_case_test_rails_app](https://github.com/tielur/display_case_test_rails_app)
Here's an example of `rails console` when I use `reload!` inside of pry.

Any advice?

```
rails c
Loading development environment (Rails 3.2.5)
2.1.2 :001 > reload!
Reloading...
TypeError: superclass mismatch for class Blah2Exhibit
    from /Users/tclemens/sites/display_case_test_rails_app/app/exhibits/blah2_exhibit.rb:1:in `<top (required)>'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `load'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `block in load'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/activesupport-3.2.5/lib/active_support/dependencies.rb:245:in `load'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/display_case-0.0.9/lib/display_case/find_definitions.rb:11:in `block (2 levels) in find_definitions'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/display_case-0.0.9/lib/display_case/find_definitions.rb:10:in `each'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/display_case-0.0.9/lib/display_case/find_definitions.rb:10:in `block in find_definitions'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/display_case-0.0.9/lib/display_case/find_definitions.rb:6:in `each'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/display_case-0.0.9/lib/display_case/find_definitions.rb:6:in `find_definitions'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/display_case-0.0.9/lib/display_case/railtie.rb:6:in `block in <class:Railtie>'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/activesupport-3.2.5/lib/active_support/callbacks.rb:429:in `_run__70228025375963374__prepare__1546765089173593693__callbacks'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/activesupport-3.2.5/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/activesupport-3.2.5/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/activesupport-3.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/actionpack-3.2.5/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/actionpack-3.2.5/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/railties-3.2.5/lib/rails/console/app.rb:32:in `reload!'
    from (irb):1
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/railties-3.2.5/lib/rails/commands/console.rb:47:in `start'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/railties-3.2.5/lib/rails/commands/console.rb:8:in `start'
    from /Users/tclemens/.rvm/gems/ruby-2.1.2@dispaly_case_test/gems/railties-3.2.5/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'2.1.2 :002 > 
```

**Comment by hlcfan** [comment]
Hello,
Seems this doesn't fix problem.
I looked into this today and found if put this code into initializers, exhibits are still reload after file change, and no such `superclass mismatch` errors.
``` ruby
class Railtie < Rails::Railtie
  config.before_initialize do
    DisplayCase.module_eval do
      def self.find_definitions
        p "pass"
      end
    end
  end
end
```

Say we have 2 exhibits here:
``` ruby
class BaseExhibit; end
class BlahExhibit < BaseExhibit; end
class Blah2Exhibit < BlahExhibit; end
```

If I made some changes in `Blah2Exhibit`, it re-loads `Blah2Exhibit` file, but at meantime, `BlahExhibit` is not the previous one(different `object_id` from what i can tell), so it gives `superclass mismatch` error.

Not sure I override `find_definitions` method, but my Rails app still reload exhibits file.

**Comment by codeodor** [comment]
@hlcfan can you create an example project that I can use to check that?

Also, can you confirm you're on the latest version?

Thanks!

**Comment by hlcfan** [comment]
@codeodor 
Yes, i'm using the latest version `0.1.2`. Here is the repo: https://github.com/hlcfan/display_case_example

Step to reproduce:
+ Start your server
+ Add a record(which is a `Post` in this example)
+ Open this article just created, say `/posts/1`
+ Modify code in `render_news_title` in `NewsExhibit`, like `title.titleize + '1'`
+ Refresh page again, it gives `superclass mismatch for class NewsExhibit`.
